version: '2'

services:
    nginx:
        image: nginx:1.11.3-alpine
        volumes:
            - ./html:/var/www/html:ro
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - 80:80
            - 443:443
        links:
            - php
    
    php:
        image: php:7.0.9-fpm-alpine
        volumes:
            - ./html:/var/www/html
        links:
            - db
        env_file:
            - ./php.config.env
    
    db:
        image: mariadb:10.1.16
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        env_file:
            - ./mariadb.config.env
